name: Setup
description: Setup the environment for the different CI jobs


runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --silent
      shell: bash