name: Setup
description: Setup the environment for the different CI jobs


runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: Install dependencies
      run: bun install --frozen-lockfile --silent
      shell: bash