name: saas-monorepo-starter

services:
  postgres:
    image: postgres:18
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
