packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@t3-oss/env-core': ^0.13.8
  '@types/pg': ^8.15.6
  better-auth: ^1.4.3
  elysia: ^1.4.16
  zod: ^4.1.13
  '@types/bun': ^1.3.3

onlyBuiltDependencies:
  - lefthook
