packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@t3-oss/env-core': 0.13.8
  '@types/pg': ^8.15.6
  better-auth: ^1.4.1
  drizzle-orm: ^0.44.7
  zod: 4.1.12
  elysia: ^1.4.16

onlyBuiltDependencies:
  - lefthook
