packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@t3-oss/env-core': 0.13.8
  '@tanstack/react-form': ^1.23.0
  '@tanstack/react-query': ^5.89.0
  '@tanstack/react-query-devtools': ^5.89.0
  '@trpc/client': ^11.5.1
  '@trpc/server': 11.5.1
  '@trpc/tanstack-react-query': ^11.5.1
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  better-auth: ^1.3.13
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv-cli: ^10.0.0
  drizzle-orm: ^0.44.5
  lucide-react: ^0.544.0
  react: ^19.1.1
  react-dom: ^19.1.1
  sonner: 2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tw-animate-css: ^1.3.8
  typescript: ^5.9.2
  zod: 4.1.9

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - sharp
