packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@t3-oss/env-core": "^0.13.8"
  "better-auth": "^1.3.34"
  "zod": "^4.1.12"
  "drizzle-orm": "^0.44.7"
  "@types/pg": "^8.15.6"

onlyBuiltDependencies:
  - lefthook
