packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@convex-dev/better-auth": "^0.9.6"
  "@t3-oss/env-core": "^0.13.8"
  "better-auth": "^1.3.34"
  "dotenv-cli": "^11.0.0"
  "zod": "^4.1.12"
  "drizzle-orm": "^0.44.7"
  "@types/pg": "^8.15.6"
