FROM oven/bun:alpine AS base
WORKDIR /app

FROM base AS prepare

RUN bun add -g turbo@^2
COPY . .
RUN turbo prune @repo/web --docker

FROM base AS builder

COPY --from=prepare /app/out/json/ .
RUN bun install --frozen-lockfile --silent

COPY --from=prepare /app/out/full/ .
RUN bun build:web

FROM base AS runner

RUN addgroup --system --gid 1001 bunjs
RUN adduser --system --uid 1001 tanstack
USER tanstack

COPY --from=builder --chown=tanstack:bunjs /app/apps/web/.output ./

ARG COMMIT_HASH
ENV COMMIT_HASH=$COMMIT_HASH

ENV NODE_ENV=production

CMD ["bun", "run", "./server/index.mjs"]
